### ISSUE TITLE
netcdfcpp.h missing

### ISSUE THREAD

**Issue by jumi26** [forefireAPI/firefront#1]
Hello!

I want run your forefire model but have issues with the netcdfcpp.h file. When I run `scons` I get the error, that the netcdfcpp.h is not found. The file is missing in your repository. I have all dependencies installed. Can you please add it to your repo?

Cheers! 
Julia

**Comment by filippi** [comment]
Dear Julia,
I cannot distribute netcdfcpp.h, it is included in NetCDF-C++ >>LEGACY<< required for compatibilities issues, get it from : https://www.unidata.ucar.edu/downloads/netcdf/netcdf-cxx/index.jsp
on yum you have it with "yum install netcdf-cxx-devel"
Cheers

**Comment by antonio-leblanc** [comment]
`sudo apt install libnetcdf-dev libnetcdf-cxx-legacy-dev`  was added to Readme
https://github.com/forefireAPI/firefront/commit/32b6348669c89ef24859019b6112bb43c7e4449b
