### ISSUE TITLE
Fuel definition in ForeFire

### ISSUE THREAD

**Issue by julimi26** [forefireAPI/firefront#16]
Hi ForeFire Developers,

I have a question regarding how fuels are handled in your model. In your Aullene example you provide a fuels.ff file with various parameters for each fuel type. Can you provide the reference or further information for this table? We are currently trying to apply your model for an area in the US and struggle with setting up the fuel definitions and the required parameters. 

Cheers!
Julia

**Comment by filippi** [comment]
Hi Julia,
The parameters matches the keys that are used by the velocity model (like packing ratio, moisture of dead fine fuel...etc...). Then the fuel layer is a matrix of  indices  in this file. So actually the "fuel.ff" is dependent of the Fire velocity model of use. You will therefore find in the cpp velocity model, see https://github.com/forefireAPI/firefront/blob/master/src/Rothermel.cpp for instance. Names matches the one from Rothermels monograph.
Regards

**Comment by TobiasBauerTUM** [comment]
Hi @filippi, 
I work together with @julimi26. I think we get the concept of the `fuel.ff` file and the `landscape.nc` file, which references the defined fuels.   
As Julia mentioned, we are trying to apply that model to regions in northern America, thus we need to create our own landscape file, I guess. For that reason, we were wondering, how you created the fuels matrix within the landscape file. Is there some sort of mapping from open satellite imagery datasets, like e.g.  [ESA-Worldcover](https://esa-worldcover.org/en) to these fuel classes?

Best Regards
Tobias

**Comment by filippi** [comment]
Hi Tobias,

The dataset we have (in the fue.ff file) have been tested for some of the indices present (and matches) the Corine land cover, especially in the mediterranean region, southwest France in particular. I have no idea of the vegetation in North America, so indices may not be present or require some work to make forest association with parameters for the Rothermel model for example.  I believe a very nice dataset would be https://landfire.gov as it probably is tested. Use everything with caution for whatever usage are intended.
Regards
