### ISSUE TITLE
bmapcells files

### ISSUE THREAD

**Issue by aalonsop** [forefireAPI/firefront#21]
Context :
MNH coupled simulation. Input forefire : burning map file containing the arrival time matrix and the active cells matrix.

Issue : 
When setting all cells to active (all matrix coefficients are equal to 1), there is a _bmapcells_ files created per processor even for the areas where there are not any burning cells. 
The expected behaviour is that _bmapcells_ files are only created for the processors which contain burning cells.

**Comment by filippi** [comment]
Sorry... these must be there since data is valued at the beginning, but only read once.
