### ISSUE TITLE
forefire bmap output

### ISSUE THREAD

**Issue by aalonsop** [forefireAPI/firefront#22]
Context :
Normal forefire simulation with the line "save[]" in the 'run.ff' file.

Issue : 
If the atmospherical grid is specified (for example : "setParameters[atmoNX=242;atmoNY=102]) then the refYear and refDay of the output netcdf file will contain the refYear and refDay of the lpsimple.nc file . 
If the atmospherical grid is not specified then the default parameters are 'refYear=2012' and 'refDay=1'.

**Comment by filippi** [comment]
added a new plot[] function, and date parameter should be fixed
