### ISSUE TITLE
Use in my region

### ISSUE THREAD

**Issue by Nikolaos96** [forefireAPI/firefront#24]
In order to use it for my area, is it enough to change only the coordinates where the fire starts?

**Comment by ludobegins** [comment]
You will need a landscape file for your region of interest. Please refer to the [wiki](https://github.com/forefireAPI/firefront/wiki/3.-Configuration) for more details.

**Comment by Nikolaos96** [comment]
Thank you for your response. Could you help me a bit more on how to make the landscape file please. How do I use the landscape_gen_funcs.py program?

Do you have an example code that creates this file?

Thank you.

**Comment by Nikolaos96** [comment]
I read the py3_tools/landscape_eda.ipynbfile and understood that it contains the data for altitude, fuel, wind.
If I assume that the same data applies to my area, why doesn't it work?

Thank you.

**Comment by filippi** [comment]
You have to create similar file for your area for it to work. 
Regards

**Comment by Nikolaos96** [comment]
The fuctions in py3_tools/forefirepy/landscape_gen_funcs.py can be used to generate the file landscape ?

Thank you.

**Comment by filippi** [comment]
Yes indeed, 
And it will require to generate base data such as potential wind for every directions, find fuel data, classify it... as it very much depends on what data is available in your region, there are unfortunately no reals standard/general way to generate this base data.

**Comment by Nikolaos96** [comment]
Well, I will have to find the corresponding files for my area fuel.tif, elevation.tif so I can run the example_landscape_gen function and it will generate the custom_landscape.nc for my area.
Correctly ?

Thank you.

**Comment by filippi** [comment]
Hi,
Yes that and a netcdf file for precomputed wind in 8 direction using a mass conserving solver.

**Comment by Nikolaos96** [comment]
where can i find your fuel.tif file to match fuel.ff ?
i will run program py3_tools/forefirepy/landscape_gen_funcs.py with your fuel.tif file and my elevation.tif file.

Thank you.

**Comment by filippi** [comment]
Hi,
The fuel field is already in a sample netcdf. Fuel.tif  is the fuel distribution, It would maybe make little sense to take land use of somewhere with the elevation of somewhere else and a corresponding fuel.ff that you should do yourself to match your fuel indices. See https://github.com/forefireAPI/firefront/blob/master/doc/UserGuide/ForeFireUserGuide.pdf.

We are sorry, but this code is intended mainly for combustionists or fire analysts that are also developers and handle numerics, it do require an advance knowledge and practice in Python, C++, GDAL, mostly under Unix platforms. For more user friendly approaches you have FlamMap from USFS which would provide similar results.

Also, we do collaborate with people in many countries especially in Europe, if you tell me from where you are, I can maybe guess someone near you that could help (or already did the job)

Regards

**Comment by Nikolaos96** [comment]
I'm from Athens, Greece.
I have found the elevetion.tif file for my region.I need the find file fuels.tif and fuels.ff for my region.

**Comment by Nikolaos96** [comment]
I'm running the example you have and I want to change the direction of the wind.
Can I set the wind direction inside the aullene.ff file?

Thank you.

**Comment by filippi** [comment]
Hi.. I am sorry, We have something for Crete, not for Athens. As for the wind, you need to re-generate potential wind for your region using a mass consistant solver first.

**Comment by Nikolaos96** [comment]
So I can't run your example for a different wind direction?

I saw that I can change the wind speed from the command 
trigger[wind;loc=(0.,0.,0.);vel=(7.458691406250001,6.4,0.);t=0.]

**Comment by filippi** [comment]
Yes it works for this dataset , Aullene, that is the activation vector for the pre computed vector field coefficients

**Comment by Nikolaos96** [comment]
I didn't understand if I can change the direction of the wind for Aullene example. 
Can I change the wind direction for your example?

Thanks and sorry for the many questions.

**Comment by filippi** [comment]
Hi,
yes in the example,
trigger[wind;loc=(0.,0.,0.);vel=(4.5,6.4,0.);t=0.]
will change the activation wind vector to 4.5 6.4 the wind field will be extrapolated from that

**Comment by Nikolaos96** [comment]
Thank you for your answers.
What is the unit of speed measurements?

**Comment by Nikolaos96** [comment]
What is the unit of measurement ?
m/s ?

Thank you.

**Comment by filippi** [comment]
Hi
yes meter per second
********************************************
    Jean-Baptiste Filippi
    Chargé de Recherches
    SPE - UMR 6134 CNRS
    Université de Corse
    Quartier grossetti
    BP 52, 20250 Corte
    Tel. +33 495 450 158
******************************************
