### ISSUE TITLE
hardcoded fuel moisture of extinction value on Rothermel model

### ISSUE THREAD

**Issue by agumartina** [forefireAPI/firefront#35]
The fuel moisture of extinction (me from the tables) value for Rothermel model has a hardcode value and the value from the fuel table is ignored.
https://github.com/forefireAPI/firefront/blob/edbcdf90bbb610b69ed56a4b2bc9ebf9beb06f82/src/Rothermel.cpp#L173

Is this intentional?  Scott & Burgan models between 15% and 40%. So some fuels stop burning earlier/later than others.

**Comment by filippi** [comment]
Hi ! Thansk for watching so deep.
yes, it is hardcoded, so it is compatible with the Balbi models fuel files, please have a loot at the RothermelAndrews2018.cpp if you want a more referenced implementation.
or you can generate your own with WildfireROsModels python lib also in the same foreFireAPI organisation.
moreover, beware, this one is expecting metric system values.. which is not conventional.

**Comment by agumartina** [comment]
Thank you for your fast response @filippi I will take a look
